# -*- coding: utf-8 -*-
"""AI GUARDRAILS PROMPT INJECTION SYSTEM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B475ez3xpAUqq3k6nsE24ylq0Ept0wTO

#  CELL 1 :Installing Packages and Libraries
"""
# "pip install -q langchain langchain-google-genai transformers torch"
"""#Cell 2 — Import libraries"""

import os

from transformers import pipeline

from langchain.chat_models import init_chat_model
from langchain.agents import create_agent
from langchain.agents.middleware import before_model
from langchain.tools import tool

"""# Cell 3 — Get Google API key"""
import os
import gradio as gr
from dotenv import load_dotenv

load_dotenv()

google_api_key = os.getenv("gemini_key")


"""#Cell 4 — Create Gemini model"""

llm = init_chat_model(
    "google_genai:gemini-3.6-flash",
    api_key=google_api_key
)

"""# Cell 5 — Create inbox"""

INBOX = [
    {
        "id": 1,
        "from": "john@example.com",
        "subject": "Invoice",
        "body": "Can you confirm the total for last month?"
    },
    {
        "id": 2,
        "from": "alice@example.com",
        "subject": "Refund",
        "body": "I was charged twice. Please help."
    }
]

"""# Cell 6 — Search emails tool"""

@tool
def search_emails(query: str) -> list[dict]:
    """Searches emails in the inbox based on a query."""
    q = query.lower()

    return [
        email
        for email in INBOX
        if q in (
            email["from"] +
            email["subject"] +
            email["body"]
        ).lower()
    ]

"""# Cell 7 — Draft reply tool

"""

@tool
def draft_reply(email_id: int, reply: str):
    """Drafts a reply to an email."""
    return f"Draft saved for email {email_id}: {reply}"

"""# Cell 8 — Send email tool"""

@tool
def send_email(to: str, subject: str, body: str):
    """Sends an email to a specified recipient with a subject and body."""
    return f"Email sent to {to}: {subject}"

"""# Cell 9 — System prompt"""

system_prompt = """
You are a helpful email assistant.
You can search emails, draft replies, and send emails.
When a user asks for an email-related task, use the relevant tool.
"""

"""# Cell 10 — Load prompt injection model"""

injection_clf = pipeline(
    "text-classification",
    model="protectai/deberta-v3-base-prompt-injection-v2"
)

"""# Cell 11 — Create prompt injection guardrail"""

@before_model
def block_injections(state, runtime):
    last_user_content = state["messages"][-1].content

    # Ensure last_user_content is a string and not empty
    if not isinstance(last_user_content, str) or not last_user_content.strip():
        print("Info: Skipping injection check: last_user_content is not a string or is empty.")
        return

    results = injection_clf(last_user_content)

    if not results: # Check if the list is empty
        print(f"Warning: Prompt injection classifier returned an empty result for input: '{last_user_content}'. Allowing by default.")
        return

    result = results[0]

    # Increased the threshold to 1.0 to effectively disable the guardrail for now
    if result["label"] == "INJECTION" and result["score"] > 0.8:
        raise ValueError(
            f"Blocked: prompt injection detected ({result['score']:.2f})"
        )

"""# Cell 12 — Create agent"""

agent = create_agent(
    model=llm,
    tools=[
        search_emails,
        draft_reply,
        send_email
    ],
    system_prompt=system_prompt,
    debug=True,
    middleware=[block_injections]
)



#now we need to create a gradio interface to test the guardrail

def check_prompt(prompt):
    try:
        response = agent.invoke({
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        })

        return "✅ SAFE", response["messages"][-1].content

    except ValueError as e:
        return "🚫 BLOCKED", str(e)

demo = gr.Interface(
    fn=check_prompt,
    inputs=gr.Textbox(
        label="Enter your prompt",
        placeholder="Type a prompt..."
    ),
    outputs=[
        gr.Textbox(label="Guardrail Result"),
        gr.Textbox(label="AI Response")
    ],
    title="Prompt Injection Guardrail",
    description="Checks user prompts before sending them to the LLM."
)

if __name__ == "__main__":
    demo.launch(share=True)